language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t fpiantini/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true fpiantini/docker-react npm run test