FROM node:alpine
WORKDIR /app
COPY package.json .
RUN npm install

# This is not strictly necessary due to the usage of volumes
# but we need this copy when we run tests (e.g. when using Travis CI)
COPY . .

 CMD ["npm", "run", "start"]
